
      let baby = "Baby Shark";
      let doo = "doo-doo doo-doo";
      let a = "Mommy Shark";
      let b = "Daddy Shark";
      let c = "Grandma Shark";
      let v = "Grandpa Shark";
      let t = "Lets go hunt";
      let n = "Run away";
      let m = "Safe at last";
      let f = "Its the end";
      let ah = "(ah!)";
      let ph = "(phew)";

      console.log(baby, doo);
      console.log(baby, doo);
      console.log(baby, doo);
      console.log(baby);
      console.log(a, doo);
      console.log(a, doo);
      console.log(a, doo);
      console.log(a);
      console.log(b, doo);
      console.log(b, doo);
      console.log(b, doo);
      console.log(b);
      console.log(c, doo);
      console.log(c, doo);
      console.log(c, doo);
      console.log(c);
      console.log(v, doo);
      console.log(v, doo);
      console.log(v, doo);
      console.log(v);
      console.log(t, doo);
      console.log(t, doo);
      console.log(t, doo);
      console.log(t);
      console.log(n, doo);
      console.log(n, doo);
      console.log(n, doo);
      console.log(n, ah);
      console.log(m, doo);
      console.log(m, doo);
      console.log(m, doo);
      console.log(m, ph);
      console.log(f, doo);
      console.log(f, doo);
      console.log(f, doo);
      console.log(f);
 