let number = "10";
console.log(typeof 10);
let message = "hi";
console.log(typeof message);
let nu = "true";
console.log(typeof true);
let numb;
console.log(typeof numb);
let numberl="";
console.log(typeof "");